from Card import Card
from Faction import Faction


class CardList:
    cards = [
        Card("2B", 6, 10, 4, 8, Faction.NONE, 5, "2b_card_icon1.png"),
        Card("2P", 4, 8, 10, 6, Faction.NONE, 5, "2p_card_icon1.png"),
        Card("4th-make Cuchulainn", 8, 1, 7, 6, Faction.NONE, 3, "4th-make_cuchulainn_card_icon1.png"),
        Card("4th-make Shemhazai", 1, 6, 7, 8, Faction.NONE, 3, "4th-make_shemhazai_card_icon1.png"),
        Card("9S", 4, 8, 6, 10, Faction.NONE, 5, "9s_card_icon1.png"),
        Card("Adamantoise", 5, 7, 4, 4, Faction.NONE, 2, "Adamantoise_card_icon2.png"),
        Card("Adrammelech", 6, 1, 7, 8, Faction.NONE, 3, "Adrammelech_card_icon1.png"),
        Card("Ahriman", 5, 5, 2, 2, Faction.NONE, 1, "Ahriman_card_icon1.png"),
        Card("Alexander Prime", 7, 3, 2, 8, Faction.PRIMAL, 3, "Alexander_prime_card_icon2.png"),
        Card("Alpha", 6, 6, 6, 6, Faction.NONE, 3, "Alpha_card_icon1.png"),
        Card("Alphinaud & Alisaie", 9, 3, 3, 9, Faction.SCIONS, 4, "Alphinaud_and_alisaie_card_icon1.png"),
        Card("Amalj'aa", 1, 4, 7, 1, Faction.BEASTMAN, 1, "Amaljaa_card_icon1.png"),
        Card("Amaro", 1, 7, 2, 3, Faction.NONE, 1, "Amaro_card_icon1.png"),
        Card("Amon the Undying", 8, 7, 3, 3, Faction.NONE, 3, "Amon_the_undying_card_icon1.png"),
        Card("Ananta", 3, 7, 5, 2, Faction.BEASTMAN, 2, "Ananta_card_icon1.png"),
        Card("Ango", 4, 2, 7, 4, Faction.NONE, 2, "Ango_card_icon1.png"),
        Card("Anima", 5, 1, 9, 9, Faction.PRIMAL, 4, "Anima_card_icon1.png"),
        Card("Apkallu", 3, 4, 4, 1, Faction.NONE, 1, "Apkallu_card_icon2.png"),
        Card("Archaeornis", 5, 4, 6, 5, Faction.NONE, 2, "Archaeornis_card_icon1.png"),
        Card("Archaeotania", 10, 9, 7, 1, Faction.NONE, 5, "Archaeotania_card_icon1.png"),
        Card("Archbishop Thordan VII", 7, 1, 10, 9, Faction.NONE, 5, "Archbishop_thordan_vii_card_icon1.png"),
        Card("Ardbert", 1, 9, 9, 9, Faction.NONE, 5, "Ardbert_card_icon1.png"),
        Card("Arenvald Lentinus", 8, 4, 8, 2, Faction.SCIONS, 3, "Arenvald_lentinus_card_icon1.png"),
        Card("Argath Thadalfus", 9, 2, 5, 8, Faction.NONE, 4, "Argath_thadalfus_card_icon1.png"),
        Card("Argos", 7, 3, 7, 1, Faction.NONE, 2, "Argos_card_icon1.png"),
        Card("Arkasodara", 4, 4, 7, 4, Faction.BEASTMAN, 2, "Arkasodara_card_icon1.png"),
        Card("Armored Weapon", 3, 5, 9, 7, Faction.GARLEAN, 4, "Armored_weapon_card_icon2.png"),
        Card("Artoirel de Fortemps", 4, 7, 3, 7, Faction.NONE, 3, "Artoirel_de_fortemps_card_icon1.png"),
        Card("Asahi sas Brutus", 8, 4, 1, 8, Faction.GARLEAN, 3, "Asahi_sas_brutus_card_icon1.png"),
        Card("Aymeric", 1, 5, 9, 9, Faction.NONE, 4, "Aymeric_card_icon1.png"),
        Card("Azeyma", 7, 6, 1, 8, Faction.NONE, 3, "Azeyma_card_icon1.png"),
        Card("Azulmagia", 4, 8, 6, 6, Faction.NONE, 3, "Azulmagia_card_icon1.png"),
        Card("Baderon Tenfingers", 3, 7, 5, 5, Faction.NONE, 2, "Baderon_tenfingers_card_icon1.png"),
        Card("Bahamut", 9, 5, 9, 6, Faction.NONE, 5, "Bahamut_card_icon1.png"),
        Card("Bandersnatch", 6, 6, 3, 4, Faction.NONE, 2, "Bandersnatch_card_icon1.png"),
        Card("Bartz Klauser", 4, 4, 10, 10, Faction.NONE, 5, "Bartz_klauser_card_icon1.png"),
        Card("Batsquatch", 6, 2, 8, 6, Faction.NONE, 3, "Batsquatch_card_icon1.png"),
        Card("Behemoth", 7, 8, 4, 2, Faction.NONE, 3, "Behemoth_card_icon1.png"),
        Card("Belladonna", 3, 7, 3, 7, Faction.NONE, 3, "Belladonna_card_icon1.png"),
        Card("Biggs & Wedge", 5, 3, 7, 5, Faction.NONE, 2, "Biggs_and_wedge_card_icon1.png"),
        Card("Bismarck", 1, 9, 7, 8, Faction.PRIMAL, 4, "Bismarck_card_icon1.png"),
        Card("Blue Dragon", 2, 2, 7, 7, Faction.NONE, 2, "Blue_dragon_card_icon1.png"),
        Card("Bomb", 3, 4, 3, 3, Faction.NONE, 1, "Bomb_card_icon1.png"),
        Card("Brachiosaur", 8, 4, 5, 4, Faction.NONE, 3, "Brachiosaur_card_icon1.png"),
        Card("Brendt, Brennan, & Bremondt", 4, 7, 6, 5, Faction.NONE, 3, "Brendt,_brennan,_&_bremondt_card_icon2.png"),
        Card("Brute Justice", 7, 7, 7, 7, Faction.NONE, 4, "Brute_justice_card_icon1.png"),
        Card("Byakko", 7, 1, 7, 7, Faction.NONE, 3, "Byakko_card_icon1.png"),
        Card("Byblos", 8, 4, 1, 7, Faction.NONE, 3, "Byblos_card_icon1.png"),
        Card("Calcabrina", 6, 6, 6, 3, Faction.NONE, 3, "Calcabrina_card_icon1.png"),
        Card("Calofisteri", 5, 8, 7, 8, Faction.NONE, 4, "Calofisteri_card_icon1.png"),
        Card("Carvallain de Gorgagne", 2, 7, 7, 2, Faction.NONE, 2, "Carvallain_de_gorgagne_card_icon1.png"),
        Card("Cecil Harvey", 4, 10, 4, 10, Faction.NONE, 5, "Cecil_harvey_card_icon1.png"),
        Card("Chapuli", 7, 2, 2, 6, Faction.NONE, 2, "Chapuli_card_icon1.png"),
        Card("Charibert", 7, 8, 4, 3, Faction.NONE, 3, "Charibert_card_icon1.png"),
        Card("Chi", 8, 1, 9, 7, Faction.NONE, 4, "Chi_card_icon1.png"),
        Card("Chimera", 7, 7, 2, 2, Faction.NONE, 2, "Chimera_card_icon1.png"),
        Card("Chocobo", 3, 7, 2, 1, Faction.NONE, 1, "Chocobo_card_icon1.png"),
        Card("Cid Garlond", 5, 9, 9, 2, Faction.NONE, 4, "Cid_garlond_card_icon1.png"),
        Card("Cirina", 3, 5, 6, 8, Faction.NONE, 3, "Cirina_card_icon1.png"),
        Card("Cloud Strife", 9, 3, 9, 8, Faction.NONE, 5, "Cloud_strife_card_icon1.png"),
        Card("Cloud of Darkness", 7, 10, 7, 6, Faction.NONE, 5, "Cloud_of_darkness_card_icon1.png"),
        Card("Coblyn", 3, 3, 3, 4, Faction.NONE, 1, "Coblyn_card_icon1.png"),
        Card("Coeurl", 2, 5, 2, 5, Faction.NONE, 1, "Coeurl_card_icon1.png"),
        Card("Coeurlregina", 5, 5, 5, 8, Faction.NONE, 3, "Coeurlregina_card_icon1.png"),
        Card("Colibri", 6, 1, 4, 1, Faction.NONE, 1, "Colibri_card_icon2.png"),
        Card("Count Edmont de Fortemps", 1, 8, 3, 8, Faction.NONE, 3, "Count_edmond_de_fortemps_card_icon1.png"),
        Card("Crawler", 7, 7, 3, 2, Faction.NONE, 2, "Crawler_card_icon1.png"),
        Card("Curator", 4, 6, 4, 7, Faction.NONE, 3, "Curator_card_icon1.png"),
        Card("Daivadipa", 7, 8, 1, 9, Faction.NONE, 4, "Daivadipa_card_icon1.png"),
        Card("Darkscale", 2, 8, 4, 7, Faction.NONE, 3, "Darkscale_card_icon1.png"),
        Card("Dawon", 8, 4, 6, 6, Faction.GARLEAN, 3, "Dawon_card_icon1.png"),
        Card("Deepeye", 1, 3, 7, 2, Faction.NONE, 1, "Deepeye_card_icon1.png"),
        Card("Delivery Moogle", 5, 5, 6, 3, Faction.BEASTMAN, 2, "Delivery_moogle_card_icon2.png"),
        Card("Demon Wall", 6, 7, 2, 3, Faction.NONE, 2, "Demon_wall_card_icon1.png"),
        Card("Dhalmel", 6, 5, 3, 5, Faction.NONE, 2, "Dhalmel_card_icon1.png"),
        Card("Diablo Armament", 4, 4, 9, 9, Faction.NONE, 4, "The_diablo_armament_card_icon1.png"),
        Card("Diabolos Hollow", 4, 4, 8, 9, Faction.NONE, 4, "Diabolos_hollow_card_icon2.png"),
        Card("Diamond Weapon", 9, 8, 7, 1, Faction.GARLEAN, 4, "The_diamond_weapon_card_icon1.png"),
        Card("Dodo", 4, 2, 3, 4, Faction.NONE, 1, "Dodo_card_icon1.png"),
        Card("Dvergr", 4, 5, 3, 7, Faction.NONE, 2, "Dvergr_card_icon1.png"),
        Card("Dwarf", 2, 4, 6, 2, Faction.BEASTMAN, 1, "Dwarf_card_icon1.png"),
        Card("Ea", 5, 4, 1, 4, Faction.NONE, 1, "Ea_card_icon1.png"),
        Card("Echidna", 6, 4, 7, 4, Faction.NONE, 3, "Echidna_card_icon1.png"),
        Card("Eden's Promise", 10, 5, 8, 6, Faction.NONE, 5, "Edens_promise_card_icon1.png"),
        Card("Ehll Tou", 1, 7, 1, 7, Faction.NONE, 2, "Ehll_tou_card_icon1.png"),
        Card("Ejika Tsunjika", 7, 1, 1, 7, Faction.NONE, 2, "Ejika_tsunjika_card_icon1.png"),
        Card("Elidibus", 8, 4, 9, 4, Faction.NONE, 4, "Elidibus_card_icon1.png"),
        Card("Emerald Weapon", 7, 1, 9, 8, Faction.GARLEAN, 4, "The_emerald_weapon_card_icon1.png"),
        Card("Emmanellain de Fortemps", 7, 4, 7, 3, Faction.NONE, 3, "Emmanellain_de_fortemps_card_icon1.png"),
        Card("Endsinger", 7, 10, 2, 9, Faction.NONE, 5, "Endsinger_card_icon1.png"),
        Card("Endwalker Alphinaud & Alisaie", 4, 9, 9, 3, Faction.SCIONS, 4, "Endwalker_alphinaud_and_alisaie_card_icon1.png"),
        Card("Eros", 6, 2, 6, 8, Faction.NONE, 3, "Eros_card_icon1.png"),
        Card("Estinien", 8, 8, 2, 3, Faction.NONE, 3, "Estinien_card_icon1.png"),
        Card("Evil Weapon", 7, 2, 2, 2, Faction.NONE, 1, "Evil_weapon_card_icon1.png"),
        Card("F'lhaminn", 9, 7, 3, 7, Faction.SCIONS, 4, "Flhaminn_card_icon1.png"),
        Card("Fat Chocobo", 5, 5, 5, 5, Faction.NONE, 2, "Fat_chocobo_card_icon1.png"),
        Card("Fenrir", 7, 3, 6, 4, Faction.NONE, 3, "Fenrir_card_icon1.png"),
        Card("Feo Ul", 7, 5, 5, 1, Faction.BEASTMAN, 2, "Feo_ul_card_icon1.png"),
        Card("Ferdiad", 4, 6, 8, 4, Faction.NONE, 3, "Ferdiad_card_icon1.png"),
        Card("Firion", 10, 5, 10, 1, Faction.NONE, 5, "Firion_card_icon1.png"),
        Card("Flower Basket", 2, 2, 2, 7, Faction.NONE, 1, "Flower_basket_card_icon1.png"),
        Card("Fordola rem Lupis", 5, 8, 6, 3, Faction.NONE, 3, "Fordola_rem_lupis_card_icon1.png"),
        Card("Forgiven Obscenity", 8, 7, 1, 6, Faction.NONE, 3, "Forgiven_obscenity_card_icon1.png"),
        Card("Formidable", 8, 5, 5, 5, Faction.NONE, 3, "Formidable_card_icon1.png"),
        Card("Fourchenault Leveilleur", 7, 7, 3, 7, Faction.NONE, 3, "Fourchenault_leveilleur_card_icon1.png"),
        Card("Frixio", 6, 2, 6, 6, Faction.BEASTMAN, 2, "Frixio_card_icon1.png"),
        Card("Fuath", 7, 4, 6, 2, Faction.BEASTMAN, 2, "Fuath_card_icon1.png"),
        Card("G-Warrior", 9, 1, 7, 8, Faction.NONE, 4, "G-warrior_card_icon1.png"),
        Card("Gaelicat", 4, 1, 1, 7, Faction.NONE, 1, "Gaelicat_card_icon1.png"),
        Card("Gaia", 5, 9, 1, 9, Faction.NONE, 4, "Gaia_card_icon1.png"),
        Card("Gaius van Baelsar", 4, 10, 5, 9, Faction.GARLEAN, 5, "Gaius_van_baelsar_card_icon1.png"),
        Card("Garuda", 7, 6, 1, 7, Faction.PRIMAL, 3, "Garuda_card_icon1.png"),
        Card("Genbu", 7, 7, 1, 7, Faction.NONE, 3, "Genbu_card_icon1.png"),
        Card("Gerolt", 1, 7, 3, 7, Faction.NONE, 2, "Gerolt_card_icon1.png"),
        Card("Gibrillont", 2, 6, 3, 6, Faction.NONE, 2, "Gibrillont_card_icon1.png"),
        Card("Gigantender", 7, 4, 4, 4, Faction.NONE, 2, "Gigantender_card_icon1.png"),
        Card("Gigi", 6, 8, 4, 7, Faction.NONE, 4, "Gigi_card_icon1.png"),
        Card("Gilgamesh & Enkidu", 8, 3, 7, 3, Faction.NONE, 3, "Gilgamesh_and_enkidu_card_icon1.png"),
        Card("Gnath", 6, 3, 7, 3, Faction.BEASTMAN, 2, "Gnath_card_icon1.png"),
        Card("Gnoll", 2, 4, 7, 6, Faction.NONE, 2, "Gnoll_card_icon1.png"),
        Card("Godbert Manderville", 6, 6, 5, 6, Faction.NONE, 3, "Godbert_manderville_card_icon1.png"),
        Card("Gogo, Master of Mimicry", 8, 6, 4, 6, Faction.NONE, 3, "Gogo,_master_of_mimicry_card_icon1.png"),
        Card("Gold Saucer Attendant", 4, 7, 1, 6, Faction.NONE, 2, "Gold_saucer_attendant_card_icon1.png"),
        Card("Goobbue", 2, 5, 5, 2, Faction.NONE, 1, "Goobbue_card_icon1.png"),
        Card("Good King Moggle Mog XII", 7, 6, 7, 1, Faction.PRIMAL, 3, "Good_king_moggle_mog_xiii_card_icon1.png"),
        Card("Gosetsu", 10, 5, 10, 2, Faction.NONE, 5, "Gosetsu_card_icon1.png"),
        Card("Great Azuro", 4, 7, 1, 1, Faction.NONE, 1, "The_great_azuro_card_icon1.png"),
        Card("Great Gold Whisker", 6, 9, 6, 7, Faction.BEASTMAN, 4, "Great_gold_whisker_card_icon1.png"),
        Card("Grenoldt", 1, 3, 7, 7, Faction.NONE, 2, "Grenoldt_card_icon1.png"),
        Card("Griffin", 5, 1, 7, 8, Faction.NONE, 3, "Griffin_card_icon1.png"),
        Card("Grynewaht", 7, 4, 7, 4, Faction.GARLEAN, 3, "Grynewaht_card_icon1.png"),
        Card("Guidance Node", 6, 4, 4, 4, Faction.NONE, 2, "Guidance_node_card_icon1.png"),
        Card("Hades", 8, 6, 6, 10, Faction.NONE, 5, "Hades_card_icon1.png"),
        Card("Hancock", 8, 9, 1, 7, Faction.NONE, 4, "Hancock_card_icon1.png"),
        Card("Happy Bunny", 3, 8, 7, 3, Faction.NONE, 3, "Happy_bunny_card_icon1.png"),
        Card("Hatamoto", 2, 7, 5, 6, Faction.NONE, 2, "Hatamoto_card_icon1.png"),
        Card("Haurchefant", 7, 1, 5, 8, Faction.NONE, 3, "Haurchefant_card_icon1.png"),
        Card("Heavensward Thancred", 8, 1, 7, 9, Faction.SCIONS, 4, "Heavensward_thancred_card_icon2.png"),
        Card("Heavensward Y'shtola", 9, 9, 2, 5, Faction.SCIONS, 4, "Heavensward_yshtola_card_icon2.png"),
        Card("Hermes", 6, 8, 7, 1, Faction.NONE, 3, "Hermes_card_icon1.png"),
        Card("Hien", 2, 10, 5, 10, Faction.NONE, 5, "Hien_card_icon1.png"),
        Card("Hilda", 1, 4, 8, 8, Faction.NONE, 3, "Hilda_card_icon1.png"),
        Card("Hildibrand & Nashu Mhakaracca", 1, 8, 10, 8, Faction.NONE, 5, "Hildibrand_and_nashu_mhakaracca_card_icon1.png"),
        Card("Hiruko", 4, 7, 5, 7, Faction.NONE, 3, "Hiruko_card_icon1.png"),
        Card("Hisui & Kurenai", 10, 2, 7, 9, Faction.NONE, 5, "Hisui_and_kurenai_card_icon1.png"),
        Card("Hoary Boulder & Coultenet", 2, 7, 2, 7, Faction.SCIONS, 2, "Hoary_boulder_&_coultenet_card_icon1.png"),
        Card("Hobgoblin", 2, 7, 2, 2, Faction.NONE, 1, "Hobgoblin_card_icon1.png"),
        Card("Honoroit", 7, 2, 7, 2, Faction.NONE, 2, "Honoroit_card_icon1.png"),
        Card("Hraesvelgr", 7, 7, 10, 6, Faction.NONE, 5, "Hraesvelgr_card_icon1.png"),
        Card("Hrodric Poisontongue", 2, 7, 6, 7, Faction.NONE, 3, "Hrodric_poisontongue_card_icon1.png"),
        Card("Huaca", 7, 5, 8, 2, Faction.NONE, 3, "Huaca_card_icon1.png"),
        Card("Hydaelyn", 10, 3, 10, 5, Faction.PRIMAL, 5, "Hydaelyn_card_icon1.png"),
        Card("Hythlodaeus", 7, 9, 6, 6, Faction.NONE, 4, "Hythlodaeus_card_icon1.png"),
        Card("Ifrit", 7, 1, 6, 7, Faction.PRIMAL, 3, "Ifrit_card_icon1.png"),
        Card("Iguana", 3, 5, 6, 5, Faction.NONE, 2, "Iguana_card_icon1.png"),
        Card("Innocence", 8, 3, 8, 8, Faction.NONE, 4, "Innocence_card_icon1.png"),
        Card("Ixal", 6, 1, 3, 4, Faction.BEASTMAN, 1, "Ixal_card_icon1.png"),
        Card("Jongleurs of Eulmore", 4, 4, 7, 6, Faction.NONE, 3, "Jongleurs_of_eulmore_card_icon1.png"),
        Card("Julyan Manderville", 6, 6, 5, 7, Faction.NONE, 3, "Julyan_manderville_card_icon1.png"),
        Card("Kal Myhk", 1, 8, 4, 8, Faction.NONE, 3, "Kal_myhk_card_icon1.png"),
        Card("Kan-E-Senna", 9, 10, 1, 7, Faction.NONE, 5, "Kan-e-senna_card_icon1.png"),
        Card("Karakuri Hanya", 7, 1, 1, 4, Faction.NONE, 1, "Karakuri_hanya_card_icon1.png"),
        Card("Keeper of the Keys", 5, 4, 4, 7, Faction.NONE, 2, "Keeper_of_the_keys_card_icon1.png"),
        Card("Kobold", 2, 2, 4, 6, Faction.BEASTMAN, 1, "Kobold_card_icon1.png"),
        Card("Koja", 3, 2, 1, 6, Faction.NONE, 1, "Koja_card_icon1.png"),
        Card("Kojin", 4, 5, 5, 4, Faction.BEASTMAN, 2, "Kojin_card_icon1.png"),
        Card("Kotokaze", 5, 6, 2, 6, Faction.NONE, 2, "Kotokaze_card_icon1.png"),
        Card("Kraken", 3, 6, 6, 6, Faction.NONE, 3, "Kraken_card_icon1.png"),
        Card("Krile", 2, 8, 8, 7, Faction.SCIONS, 4, "Krile_card_icon1.png"),
        Card("Kuribu", 8, 3, 2, 7, Faction.NONE, 3, "Kuribu_card_icon1.png"),
        Card("Lahabrea", 4, 9, 4, 8, Faction.NONE, 4, "Lahabrea_card_icon1.png"),
        Card("Lakshmi", 3, 7, 7, 5, Faction.PRIMAL, 3, "Lakshmi_card_icon1.png"),
        Card("Laniaitte de Haillenarte", 7, 6, 3, 3, Faction.NONE, 2, "Laniaitte_de_haillenarte_card_icon1.png"),
        Card("Lava Scorpion", 3, 8, 5, 5, Faction.NONE, 3, "Lava_scorpion_card_icon2.png"),
        Card("Leannan Sith", 8, 7, 2, 4, Faction.NONE, 3, "Leannan_sith_card_icon1.png"),
        Card("Leviathan", 8, 8, 8, 1, Faction.PRIMAL, 4, "Leviathan_card_icon1.png"),
        Card("Lightning", 9, 10, 7, 10, Faction.NONE, 5, "Lightning_card_icon1.png"),
        Card("Liquid Flame", 4, 3, 6, 6, Faction.NONE, 2, "Liquid_flame_card_icon2.png"),
        Card("Livia sas Junius", 3, 7, 7, 1, Faction.GARLEAN, 2, "Livia_sas_junius_card_icon1.png"),
        Card("Lizbeth", 5, 5, 6, 4, Faction.NONE, 2, "Lizbeth_card_icon1.png"),
        Card("Lolorito Nanarito", 4, 3, 7, 3, Faction.NONE, 2, "Lolorito_nanarito_card_icon1.png"),
        Card("Loporrit", 4, 6, 6, 4, Faction.NONE, 2, "Loporrit_card_icon1.png"),
        Card("Lord and Lady Chai", 5, 1, 6, 1, Faction.NONE, 1, "Lord_and_lady_chai_card_icon1.png"),
        Card("Lost Lamb", 7, 3, 4, 5, Faction.NONE, 2, "Lost_lamb_card_icon2.png"),
        Card("Louhi", 5, 8, 2, 7, Faction.NONE, 3, "Louhi_card_icon1.png"),
        Card("Louisoix Leveilleur", 9, 4, 9, 3, Faction.NONE, 4, "Louisoix_leveilleur_card_icon1.png"),
        Card("Lucia goe Junius", 8, 2, 3, 8, Faction.NONE, 3, "Lucis_goe_junius_card_icon1.png"),
        Card("Lugus", 5, 4, 7, 7, Faction.NONE, 3, "Lugus_card_icon1.png"),
        Card("Lunar Bahamut", 8, 2, 8, 4, Faction.PRIMAL, 3, "Lunar_bahamut_card_icon1.png"),
        Card("Lunar Ifrit", 8, 3, 4, 7, Faction.PRIMAL, 3, "Lunar_ifrit_card_icon1.png"),
        Card("Lupin", 3, 3, 8, 7, Faction.BEASTMAN, 3, "Lupin_card_icon1.png"),
        Card("Lyna", 1, 8, 8, 3, Faction.NONE, 3, "Lyna_card_icon1.png"),
        Card("Lyse", 6, 9, 1, 8, Faction.SCIONS, 4, "Lyse_card_icon1.png"),
        Card("M'naago", 4, 1, 4, 7, Faction.NONE, 2, "Mnaago_card_icon1.png"),
        Card("Magitek Colossus", 6, 3, 6, 3, Faction.GARLEAN, 2, "Magitek_colossus_card_icon2.png"),
        Card("Magitek Death Claw", 4, 3, 2, 3, Faction.GARLEAN, 1, "Magitek_death_claw_card_icon2.png"),
        Card("Magitek Gunship", 3, 5, 5, 5, Faction.GARLEAN, 2, "Magitek_gunship_card_icon2.png"),
        Card("Magitek Predator", 5, 7, 4, 5, Faction.GARLEAN, 3, "Magitek_predator_card_icon2.png"),
        Card("Magitek Sky Armor", 6, 2, 6, 7, Faction.GARLEAN, 3, "Magitek_sky_armor_card_icon2.png"),
        Card("Magitek Vanguard", 3, 5, 4, 7, Faction.GARLEAN, 2, "Magitek_vanguard_card_icon2.png"),
        Card("Magnai", 6, 7, 4, 4, Faction.NONE, 3, "Magnai_card_icon1.png"),
        Card("Magus Sisters", 4, 1, 8, 8, Faction.PRIMAL, 3, "Magus_sisters_card_icon1.png"),
        Card("Mammoth", 6, 3, 8, 3, Faction.NONE, 3, "Mammoth_card_icon1.png"),
        Card("Mandragora", 4, 2, 5, 3, Faction.NONE, 1, "Mandragora_card_icon1.png"),
        Card("Manxome Molaa Ja Ja", 3, 7, 2, 8, Faction.BEASTMAN, 3, "Manxome_molaa_ja_ja_card_icon1.png"),
        Card("Matoya", 8, 3, 8, 1, Faction.NONE, 3, "Matoya_card_icon1.png"),
        Card("Memeroon", 6, 6, 6, 2, Faction.BEASTMAN, 2, "Memeroon_card_icon1.png"),
        Card("Merlwyb Bloefhiswyn", 5, 9, 10, 3, Faction.NONE, 5, "Merlwyb_bloefhiswyn_card_icon1.png"),
        Card("Meteion", 7, 1, 8, 6, Faction.NONE, 3, "Meteion_card_icon1.png"),
        Card("Midgardsormr", 3, 8, 10, 7, Faction.NONE, 5, "Midgardsormr_card_icon1.png"),
        Card("Minfilia", 9, 8, 3, 5, Faction.SCIONS, 4, "Minfilia_card_icon1.png"),
        Card("Mist Dragon", 5, 8, 5, 5, Faction.NONE, 3, "Mist_dragon_card_icon1.png"),
        Card("Mistbeard", 5, 6, 7, 6, Faction.NONE, 3, "Mistbeard_card_icon1.png"),
        Card("Moglin", 8, 5, 4, 5, Faction.BEASTMAN, 3, "Moglin_card_icon1.png"),
        Card("Momodi Modi", 7, 5, 5, 3, Faction.NONE, 2, "Momodi_modi_card_icon1.png"),
        Card("Moogle", 2, 1, 3, 7, Faction.BEASTMAN, 1, "Moogle_card_icon1.png"),
        Card("Morbol", 5, 2, 5, 2, Faction.NONE, 1, "Morbol_card_icon1.png"),
        Card("Mossling", 5, 2, 5, 1, Faction.NONE, 1, "Mossling_card_icon1.png"),
        Card("Mother Miounne", 5, 5, 3, 7, Faction.NONE, 2, "Mother_miounne_card_icon1.png"),
        Card("Mother Porxie", 3, 3, 7, 6, Faction.NONE, 2, "Mother_porxie_card_icon1.png"),
        Card("Mutamix Bubblypots", 2, 6, 6, 6, Faction.BEASTMAN, 2, "Mutamix_bubblypots_card_icon1.png"),
        Card("Muud Suud", 3, 7, 1, 7, Faction.NONE, 2, "Muud_suud_card_icon1.png"),
        Card("Nael van Darnus", 3, 9, 3, 9, Faction.GARLEAN, 4, "Nael_van_darnus_card_icon2.png"),
        Card("Nald", 8, 1, 6, 7, Faction.NONE, 3, "Nald_card_icon1.png"),
        Card("Namazu", 1, 6, 1, 5, Faction.BEASTMAN, 1, "Namazu_card_icon1.png"),
        Card("Nanamo Ul Namo", 10, 6, 4, 8, Faction.NONE, 5, "Nanamo_ul_namo_card_icon1.png"),
        Card("Nero tol Scaeva", 4, 1, 8, 7, Faction.GARLEAN, 3, "Nero_tol_scaeva_card_icon1.png"),
        Card("Nidhogg", 10, 7, 3, 8, Faction.NONE, 5, "Nidhogg_card_icon1.png"),
        Card("Noctis Lucis Caelum", 7, 10, 9, 1, Faction.NONE, 5, "Noctis_lucis_caelum_card_icon1.png"),
        Card("Nu Mou", 7, 6, 2, 4, Faction.BEASTMAN, 2, "Nu_mou_card_icon1.png"),
        Card("Odin", 8, 8, 1, 8, Faction.PRIMAL, 4, "Odin_card_icon1.png"),
        Card("Omega", 6, 9, 3, 10, Faction.NONE, 5, "Omega_card_icon1.png"),
        Card("Onion Knight", 8, 2, 8, 10, Faction.NONE, 5, "Onion_knight_card_icon1.png"),
        Card("Opo-opo", 1, 4, 2, 6, Faction.NONE, 1, "Opo-opo_card_icon2.png"),
        Card("Oracle of Light", 7, 7, 9, 4, Faction.NONE, 4, "Oracle_of_light_card_icon1.png"),
        Card("Paissa", 4, 6, 3, 6, Faction.NONE, 2, "Paissa_card_icon1.png"),
        Card("Papalymo & Yda", 3, 7, 8, 2, Faction.SCIONS, 3, "Papalymo_and_yda_card_icon1.png"),
        Card("Pazuzu", 4, 8, 4, 7, Faction.NONE, 3, "Pazuzu_card_icon1.png"),
        Card("Penthesilea", 7, 2, 8, 5, Faction.NONE, 3, "Penthesilea_card_icon1.png"),
        Card("Philia", 2, 6, 8, 6, Faction.NONE, 3, "Philia_card_icon1.png"),
        Card("Phlegethon", 1, 7, 6, 7, Faction.NONE, 3, "Phlegethon_card_icon1.png"),
        Card("Phoebad", 8, 8, 3, 1, Faction.NONE, 3, "Phoebad_card_icon1.png"),
        Card("Phoenix", 5, 9, 6, 9, Faction.PRIMAL, 5, "Phoenix_card_icon1.png"),
        Card("Pipin Tarupin", 6, 5, 6, 6, Faction.NONE, 3, "Pipin_tarupin_card_icon1.png"),
        Card("Pisaca", 3, 4, 4, 4, Faction.NONE, 1, "Pisaca_card_icon1.png"),
        Card("Poroggo", 6, 3, 7, 3, Faction.NONE, 2, "Poroggo_card_icon1.png"),
        Card("Porxie", 1, 2, 6, 4, Faction.NONE, 1, "Porxie_card_icon1.png"),
        Card("Progenitrix", 6, 6, 3, 6, Faction.NONE, 3, "Progenitrix_card_icon1.png"),
        Card("Prometheus", 6, 5, 8, 3, Faction.GARLEAN, 3, "Prometheus_card_icon1.png"),
        Card("Provenance Watcher", 7, 4, 4, 8, Faction.NONE, 3, "Provenance_watcher_card_icon1.png"),
        Card("Pudding", 2, 4, 3, 5, Faction.NONE, 1, "Pudding_card_icon1.png"),
        Card("Qiqirn Meateater", 1, 5, 7, 5, Faction.BEASTMAN, 2, "Qiqirn_meateater_card_icon1.png"),
        Card("Qitari", 4, 6, 2, 2, Faction.BEASTMAN, 1, "Qitari_card_icon1.png"),
        Card("Qitian Dasheng", 3, 8, 4, 8, Faction.NONE, 3, "Qitian_dasheng_card_icon1.png"),
        Card("Quintus van Cinna", 9, 3, 6, 8, Faction.GARLEAN, 4, "Quintus_van_cinna_card_icon1.png"),
        Card("Rampart", 1, 6, 5, 1, Faction.NONE, 1, "Rampart_card_icon1.png"),
        Card("Ramuh", 8, 1, 8, 8, Faction.PRIMAL, 4, "Ramuh_card_icon1.png"),
        Card("Ran'jit", 1, 9, 9, 5, Faction.NONE, 4, "Ran;jit_card_icon1.png"),
        Card("Rasho", 4, 7, 8, 2, Faction.NONE, 3, "Rasho_card_icon1.png"),
        Card("Raubahn & Pipin", 1, 10, 10, 6, Faction.NONE, 5, "Raubahn_and_pipin_card_icon1.png"),
        Card("Raubahn Aldynn", 6, 2, 9, 10, Faction.NONE, 5, "Raubahn_aldynn_card_icon1.png"),
        Card("Ravana", 9, 7, 8, 1, Faction.PRIMAL, 4, "Ravana_card_icon1.png"),
        Card("Raya-O-Senna & A-Ruhn-Senna", 5, 6, 6, 6, Faction.NONE, 3, "Raya-o-senna_and_a-ruhn-senna_card_icon1.png"),
        Card("Regula van Hydrus", 8, 8, 6, 8, Faction.GARLEAN, 5, "Regula_van_hydrus_card_icon1.png"),
        Card("Rhalgr", 6, 8, 7, 7, Faction.NONE, 3, "Rhalgr_card_icon1.png"),
        Card("Rhitahtyn sas Arvina", 7, 1, 3, 7, Faction.GARLEAN, 2, "Rhitahtyn_sas_arvina_card_icon1.png"),
        Card("Rhoswen", 5, 6, 4, 6, Faction.NONE, 2, "Rhoswen_card_icon1.png"),
        Card("Rofocale", 4, 7, 1, 8, Faction.NONE, 3, "Rofocale_card_icon1.png"),
        Card("Roland", 2, 7, 8, 3, Faction.NONE, 3, "Roland_card_icon1.png"),
        Card("Rolling Tankard", 6, 4, 2, 6, Faction.NONE, 2, "Rolling_tankard_card_icon1.png"),
        Card("Roundrox", 2, 2, 8, 8, Faction.NONE, 3, "Roundrox_card_icon1.png"),
        Card("Ruby Weapon", 8, 7, 1, 9, Faction.GARLEAN, 4, "Ruby_weapon_card_icon1.png"),
        Card("Runar", 6, 4, 7, 1, Faction.NONE, 2, "Runar_card_icon1.png"),
        Card("Ryne", 7, 9, 7, 1, Faction.NONE, 4, "Ryne_card_icon1.png"),
        Card("Sabotender", 4, 3, 3, 3, Faction.NONE, 1, "Sabotender_card_icon1.png"),
        Card("Sadu", 6, 6, 7, 4, Faction.NONE, 3, "Sadu_card_icon1.png"),
        Card("Sahagin", 4, 5, 3, 3, Faction.BEASTMAN, 1, "Sahagin_card_icon1.png"),
        Card("Sapphire Weapon", 1, 9, 8, 7, Faction.GARLEAN, 4, "Sapphire_weapon_card_icon1.png"),
        Card("Scarface Bugaal Ja", 6, 6, 2, 6, Faction.BEASTMAN, 2, "Scarface_bugaal_ja_card_icon1.png"),
        Card("Seeker of Solitude", 4, 6, 6, 8, Faction.NONE, 3, "Seeker_of_solitude_card_icon1.png"),
        Card("Seiryu", 7, 7, 7, 1, Faction.NONE, 3, "Seiryu_card_icon1.png"),
        Card("Senor Sabotender", 9, 5, 7, 6, Faction.NONE, 4, "Senor_sabotender_card_icon1.png"),
        Card("Sephirot", 6, 8, 8, 6, Faction.PRIMAL, 4, "Sephirot_card_icon1.png"),
        Card("Shadowbringers Thancred", 7, 9, 8, 1, Faction.SCIONS, 4, "Shadowbringers_thancred_card_icon1.png"),
        Card("Shadowbringers Urianger", 9, 2, 5, 9, Faction.SCIONS, 4, "Shadowbringers_urianger_card_icon1.png"),
        Card("Shadowbringers Warrior of Light", 2, 10, 10, 5, Faction.PRIMAL, 5, "Shadowbringers_warrior_of_light_card_icon1.png"),
        Card("Shadowbringers Y'shtola", 2, 9, 5, 9, Faction.SCIONS, 4, "Shadowbringers_y;shtola_card_icon1.png"),
        Card("Shantotto", 4, 9, 7, 9, Faction.NONE, 5, "Shantotto_card_icon1.png"),
        Card("Shinryu", 7, 8, 8, 2, Faction.PRIMAL, 4, "Shinryu_card_icon1.png"),
        Card("Shiva", 1, 8, 8, 8, Faction.PRIMAL, 4, "Shiva_card_icon1.png"),
        Card("Siegfried", 6, 6, 4, 8, Faction.NONE, 3, "Siegfried_card_icon1.png"),
        Card("Siren", 3, 6, 7, 2, Faction.NONE, 2, "Siren_card_icon1.png"),
        Card("Sophia", 10, 8, 5, 6, Faction.PRIMAL, 5, "Sophia_card_icon2.png"),
        Card("Spriggan", 2, 3, 4, 4, Faction.NONE, 1, "Spriggan_card_icon1.png"),
        Card("Squall Leonhart", 6, 10, 10, 1, Faction.NONE, 5, "Squall_leonhart_card_icon1.png"),
        Card("Storge", 6, 8, 2, 6, Faction.NONE, 3, "Storge_card_icon1.png"),
        Card("Stormblood Alphinaud & Alisaie", 6, 8, 8, 8, Faction.SCIONS, 5, "Stormblood_alphinaud_and_alisaie_card_icon1.png"),
        Card("Stormblood Gilgamesh", 9, 4, 8, 4, Faction.NONE, 4, "Stormblood_gilgamesh_card_icon1.png"),
        Card("Stormblood Tataru Taru", 1, 4, 1, 7, Faction.SCIONS, 1, "Stormblood_tataru_taru_card_icon1.png"),
        Card("Strix", 5, 7, 1, 7, Faction.NONE, 3, "Strix_card_icon2.png"),
        Card("Succubus", 7, 3, 2, 6, Faction.NONE, 2, "Succubus_card_icon1.png"),
        Card("Susano", 2, 8, 3, 8, Faction.PRIMAL, 3, "Susano_card_icon1.png"),
        Card("Suzaku", 1, 7, 7, 7, Faction.NONE, 3, "Suzaku_card_icon1.png"),
        Card("Sylph", 2, 4, 5, 4, Faction.BEASTMAN, 1, "Sylph_card_icon1.png"),
        Card("Tansui", 6, 2, 3, 7, Faction.NONE, 2, "Tansui_card_icon1.png"),
        Card("Tataru Taru", 7, 2, 3, 2, Faction.SCIONS, 1, "Tataru_card_icon1.png"),
        Card("Terra Branford", 10, 10, 2, 5, Faction.NONE, 5, "Terra_branford_card_icon1.png"),
        Card("Thal", 6, 7, 8, 1, Faction.NONE, 3, "Thal_card_icon1.png"),
        Card("Thancred", 2, 3, 8, 7, Faction.SCIONS, 3, "Thancred_card_icon1.png"),
        Card("The Griffin", 8, 8, 4, 1, Faction.NONE, 3, "Griffin_card_2_icon2.png"),
        Card("Therion", 9, 9, 2, 9, Faction.NONE, 5, "Therion_card_icon1.png"),
        Card("Tiamat", 9, 6, 5, 6, Faction.NONE, 4, "Tiamat_card_icon1.png"),
        Card("Tidus", 10, 7, 1, 9, Faction.NONE, 5, "Tidus_card_icon1.png"),
        Card("Tioman", 1, 5, 8, 7, Faction.NONE, 3, "Tioman_card_icon1.png"),
        Card("Titan", 1, 7, 7, 6, Faction.PRIMAL, 3, "Titan_card_icon1.png"),
        Card("Titania", 8, 6, 6, 2, Faction.NONE, 3, "Titania_card_icon1.png"),
        Card("Tokkapchi", 2, 6, 6, 7, Faction.NONE, 3, "Tokkapchi_card_icon1.png"),
        Card("Tonberry", 2, 2, 7, 2, Faction.NONE, 1, "Tonberry_card_icon1.png"),
        Card("Tozol Huatotl", 7, 6, 6, 2, Faction.BEASTMAN, 3, "Tozol_huatotl_card_icon2.png"),
        Card("Trinity Avowed", 8, 7, 6, 1, Faction.NONE, 3, "Trinity_avowed_card_icon1.png"),
        Card("Trinity Seeker", 6, 1, 8, 7, Faction.NONE, 3, "Trinity_seeker_card_icon1.png"),
        Card("Tsukuyomi", 2, 7, 7, 8, Faction.PRIMAL, 4, "Tsukuyomi_card_icon1.png"),
        Card("Ultima Weapon", 7, 8, 9, 1, Faction.GARLEAN, 4, "Ultima_weapon_card_icon1.png"),
        Card("Ultima, the High Seraph", 6, 10, 7, 7, Faction.NONE, 5, "Ultima,_the_high_seraph_card_icon1.png"),
        Card("Ultros & Typhon", 2, 3, 6, 7, Faction.NONE, 2, "Ultros_and_typhon_card_icon1.png"),
        Card("Unei & Doga", 6, 8, 6, 8, Faction.NONE, 4, "Unei_&_doga_card_icon1.png"),
        Card("Unknown", 5, 6, 3, 8, Faction.NONE, 3, "Unknown_card_icon1.png"),
        Card("Urianger", 8, 1, 4, 7, Faction.SCIONS, 3, "Urianger_card_icon1.png"),
        Card("Vaan", 1, 7, 10, 9, Faction.NONE, 5, "Vaan_card_icon1.png"),
        Card("Valens van Varro", 7, 5, 8, 3, Faction.GARLEAN, 3, "Valens_van_varro_card_icon1.png"),
        Card("Vanu Vanu", 2, 6, 4, 7, Faction.BEASTMAN, 2, "Vanu_vanu_card_icon1.png"),
        Card("Varis yae Galvus", 10, 10, 4, 1, Faction.GARLEAN, 5, "Varis_yae_galvus_card_icon1.png"),
        Card("Vedrfolnir", 8, 2, 7, 4, Faction.NONE, 3, "Vedrfolnir_card_icon1.png"),
        Card("Vicegerent to the Warden", 7, 1, 7, 5, Faction.NONE, 3, "Vicegerent_to_the_warden_card_icon1.png"),
        Card("Vidofnir", 8, 6, 8, 6, Faction.NONE, 4, "Vidofnir_card_icon1.png"),
        Card("Vrtra", 9, 3, 7, 7, Faction.NONE, 4, "Vrtra_card_icon1.png"),
        Card("Wanyudo & Katasharin", 6, 1, 1, 5, Faction.NONE, 1, "Wanyudo_and_katasharin_card_icon1.png"),
        Card("Warrior of Light", 10, 2, 5, 10, Faction.NONE, 5, "Warrior_of_light_card_icon1.png"),
        Card("Waukkeon", 1, 6, 7, 7, Faction.NONE, 3, "Waukkeon_card_icon1.png"),
        Card("Xande", 9, 4, 6, 7, Faction.NONE, 4, "Xande_card_icon1.png"),
        Card("Y'shtola", 7, 8, 1, 4, Faction.SCIONS, 3, "Yshtola_card_icon1.png"),
        Card("Yiazmat", 7, 6, 10, 7, Faction.NONE, 5, "Yiazmat_card_icon1.png"),
        Card("Yojimbo & Daigoro", 10, 8, 1, 8, Faction.NONE, 5, "Yojimbo_and_daigoro_card_icon1.png"),
        Card("Yotsuyu", 9, 2, 8, 6, Faction.GARLEAN, 4, "Yotsuyu_card_icon1.png"),
        Card("Ysayle", 4, 8, 8, 1, Faction.NONE, 3, "Ysayle_card_icon1.png"),
        Card("Yugiri Mistwalker", 7, 7, 1, 3, Faction.NONE, 2, "Yugiri_mistwalker_card_icon1.png"),
        Card("Yukinko", 3, 7, 3, 5, Faction.NONE, 2, "Yukinko_card_icon1.png"),
        Card("Zenos Galvus", 6, 6, 9, 9, Faction.GARLEAN, 5, "Zenos_galvus_card_icon1.png"),
        Card("Zenos yae Galvus", 6, 6, 7, 10, Faction.GARLEAN, 5, "Zenos_yae_galvus_card_icon1.png"),
        Card("Zidane Tribal", 5, 10, 6, 8, Faction.NONE, 5, "Zidane_tribal_card_icon1.png"),
        Card("Zodiark", 5, 10, 3, 10, Faction.PRIMAL, 5, "Zodiark_card_icon1.png"),
        Card("Zurvan", 3, 7, 8, 10, Faction.PRIMAL, 5, "Zurvan_card_icon2.png")
    ]
